//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Satvasoft.API.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SatvasoftEntities : DbContext
    {
        public SatvasoftEntities()
            : base("name=SatvasoftEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblAdminMenu> tblAdminMenus { get; set; }
        public virtual DbSet<tblBlogCategory> tblBlogCategories { get; set; }
        public virtual DbSet<tblBlogComment> tblBlogComments { get; set; }
        public virtual DbSet<tblBlogPost> tblBlogPosts { get; set; }
        public virtual DbSet<tblBlogPostSeeCount> tblBlogPostSeeCounts { get; set; }
        public virtual DbSet<tblBudget> tblBudgets { get; set; }
        public virtual DbSet<tblChallengeFaced> tblChallengeFaceds { get; set; }
        public virtual DbSet<tblContactU> tblContactUs { get; set; }
        public virtual DbSet<tblContactUsAttachment> tblContactUsAttachments { get; set; }
        public virtual DbSet<tblExperience> tblExperiences { get; set; }
        public virtual DbSet<tblJobOpening> tblJobOpenings { get; set; }
        public virtual DbSet<tblJobRequiredSkill> tblJobRequiredSkills { get; set; }
        public virtual DbSet<tblMenu> tblMenus { get; set; }
        public virtual DbSet<tblPortfolio> tblPortfolios { get; set; }
        public virtual DbSet<tblPortfolioFeature> tblPortfolioFeatures { get; set; }
        public virtual DbSet<tblPortfolioImage> tblPortfolioImages { get; set; }
        public virtual DbSet<tblPortfolioLogo> tblPortfolioLogoes { get; set; }
        public virtual DbSet<tblPortfolioObjective> tblPortfolioObjectives { get; set; }
        public virtual DbSet<tblPortfolioResult> tblPortfolioResults { get; set; }
        public virtual DbSet<tblPortfolioSolution> tblPortfolioSolutions { get; set; }
        public virtual DbSet<tblPortfolioTechnology> tblPortfolioTechnologies { get; set; }
        public virtual DbSet<tblPortfolioType> tblPortfolioTypes { get; set; }
        public virtual DbSet<tblProjectType> tblProjectTypes { get; set; }
        public virtual DbSet<tblRequestQuote> tblRequestQuotes { get; set; }
        public virtual DbSet<tblRoleMenu> tblRoleMenus { get; set; }
        public virtual DbSet<tblRole> tblRoles { get; set; }
        public virtual DbSet<tblSalaryRange> tblSalaryRanges { get; set; }
        public virtual DbSet<tblTechnology> tblTechnologies { get; set; }
        public virtual DbSet<tblUser> tblUsers { get; set; }
    }
}
