//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Satvasoft.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBlogPost
    {
        public int PostId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string PostImagePath { get; set; }
        public string AltTag { get; set; }
        public string PostTitle { get; set; }
        public string PostPageTitle { get; set; }
        public string PostContent { get; set; }
        public Nullable<System.DateTime> PostDate { get; set; }
        public string PostURL { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string MetaKeywords { get; set; }
        public string MetaDesc { get; set; }
        public Nullable<int> ViewCount { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
