//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Satvasoft.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblChallengeFaced
    {
        public int ChallengeFacedId { get; set; }
        public string ChallengeFaced { get; set; }
        public int PortfolioId { get; set; }
    }
}
