//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Satvasoft.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPortfolioObjective
    {
        public int ObjectiveId { get; set; }
        public string ObjectiveText { get; set; }
        public int PortfolioId { get; set; }
    
        public virtual tblPortfolio tblPortfolio { get; set; }
    }
}
