//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Satvasoft.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPortfolio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblPortfolio()
        {
            this.tblPortfolioFeatures = new HashSet<tblPortfolioFeature>();
            this.tblPortfolioImages = new HashSet<tblPortfolioImage>();
            this.tblPortfolioObjectives = new HashSet<tblPortfolioObjective>();
            this.tblPortfolioResults = new HashSet<tblPortfolioResult>();
            this.tblPortfolioSolutions = new HashSet<tblPortfolioSolution>();
            this.tblPortfolioTechnologies = new HashSet<tblPortfolioTechnology>();
        }
    
        public int PortfolioId { get; set; }
        public string Title { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string BannerImageURL { get; set; }
        public string BannerImageTooltip { get; set; }
        public Nullable<int> TechnologyId { get; set; }
        public string FrontPageImageURL { get; set; }
        public string FrontImageTooltip { get; set; }
        public string TitleSeoUrl { get; set; }
        public string SEOTitleTag { get; set; }
        public string MetaKeyword { get; set; }
        public string MetaDescription { get; set; }
        public bool RequirePageCreation { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPortfolioFeature> tblPortfolioFeatures { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPortfolioImage> tblPortfolioImages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPortfolioObjective> tblPortfolioObjectives { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPortfolioResult> tblPortfolioResults { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPortfolioSolution> tblPortfolioSolutions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPortfolioTechnology> tblPortfolioTechnologies { get; set; }
    }
}
