//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Satvasoft.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRequestQuote
    {
        public int RequestQuoteId { get; set; }
        public string FullName { get; set; }
        public string PhoneNumber { get; set; }
        public string EmailAddress { get; set; }
        public string City { get; set; }
        public string Company { get; set; }
        public int ProjectTypeId { get; set; }
        public int BudgetId { get; set; }
        public string ProjectDescription { get; set; }
        public string Attachment { get; set; }
        public string BudgetName { get; set; }
        public string ProjectTypeName { get; set; }
    }
}
