//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Satvasoft.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRoleMenu
    {
        public int RoleMenuId { get; set; }
        public int MenuId { get; set; }
        public int RoleId { get; set; }
        public bool IsView { get; set; }
        public bool IsAdd { get; set; }
        public bool IsDelete { get; set; }
        public bool IsEdit { get; set; }
    
        public virtual tblAdminMenu tblAdminMenu { get; set; }
        public virtual tblRole tblRole { get; set; }
    }
}
