//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Satvasoft.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSalaryRange
    {
        public int SalaryRangeId { get; set; }
        public string SalaryRange { get; set; }
    }
}
